"""Initial migration for PostgreSQL

Revision ID: 1eaca84a43ef
Revises: 
Create Date: 2025-12-26 02:22:24.746370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaca84a43ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_rate', sa.Float(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('late_deduction', sa.Float(), nullable=True),
    sa.Column('leave_type', sa.String(length=255), nullable=True),
    sa.Column('fine_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('industry_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=80), nullable=True),
    sa.Column('vat_gst_number', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=255), nullable=True),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('government_id', sa.String(length=255), nullable=True),
    sa.Column('cnic', sa.String(length=255), nullable=True),
    sa.Column('cnic_expiry_date', sa.String(length=255), nullable=True),
    sa.Column('domicile', sa.String(length=255), nullable=True),
    sa.Column('languages_spoken', sa.Text(), nullable=True),
    sa.Column('languages_proficiency', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=255), nullable=True),
    sa.Column('personal_phone_number', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=255), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('previous_employment', sa.Text(), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=255), nullable=True),
    sa.Column('next_of_kin_cnic', sa.String(length=255), nullable=True),
    sa.Column('next_of_kin_mobile_number', sa.String(length=255), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('temporary_address', sa.Text(), nullable=True),
    sa.Column('permanent_village', sa.String(length=255), nullable=True),
    sa.Column('permanent_post_office', sa.String(length=255), nullable=True),
    sa.Column('permanent_thana', sa.String(length=255), nullable=True),
    sa.Column('permanent_tehsil', sa.String(length=255), nullable=True),
    sa.Column('permanent_district', sa.String(length=255), nullable=True),
    sa.Column('present_village', sa.String(length=255), nullable=True),
    sa.Column('present_post_office', sa.String(length=255), nullable=True),
    sa.Column('present_thana', sa.String(length=255), nullable=True),
    sa.Column('present_tehsil', sa.String(length=255), nullable=True),
    sa.Column('present_district', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('enrolled_as', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=255), nullable=True),
    sa.Column('shift_type', sa.String(length=255), nullable=True),
    sa.Column('reporting_manager', sa.String(length=255), nullable=True),
    sa.Column('base_location', sa.String(length=255), nullable=True),
    sa.Column('interviewed_by', sa.String(length=255), nullable=True),
    sa.Column('introduced_by', sa.String(length=255), nullable=True),
    sa.Column('security_clearance', sa.String(length=255), nullable=True),
    sa.Column('basic_security_training', sa.Boolean(), nullable=True),
    sa.Column('fire_safety_training', sa.Boolean(), nullable=True),
    sa.Column('first_aid_certification', sa.Boolean(), nullable=True),
    sa.Column('agreement', sa.Boolean(), nullable=True),
    sa.Column('police_clearance', sa.Boolean(), nullable=True),
    sa.Column('fingerprint_check', sa.Boolean(), nullable=True),
    sa.Column('background_screening', sa.Boolean(), nullable=True),
    sa.Column('reference_verification', sa.Boolean(), nullable=True),
    sa.Column('guard_card', sa.Boolean(), nullable=True),
    sa.Column('guard_card_doc', sa.Text(), nullable=True),
    sa.Column('police_clearance_doc', sa.Text(), nullable=True),
    sa.Column('fingerprint_check_doc', sa.Text(), nullable=True),
    sa.Column('background_screening_doc', sa.Text(), nullable=True),
    sa.Column('reference_verification_doc', sa.Text(), nullable=True),
    sa.Column('other_certificates', sa.Text(), nullable=True),
    sa.Column('basic_salary', sa.String(length=255), nullable=True),
    sa.Column('allowances', sa.String(length=255), nullable=True),
    sa.Column('total_salary', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=255), nullable=True),
    sa.Column('bank_accounts', sa.Text(), nullable=True),
    sa.Column('system_access_rights', sa.Text(), nullable=True),
    sa.Column('employment_status', sa.String(length=255), nullable=True),
    sa.Column('last_site_assigned', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('retired_from', sa.Text(), nullable=True),
    sa.Column('service_unit', sa.String(length=255), nullable=True),
    sa.Column('service_rank', sa.String(length=255), nullable=True),
    sa.Column('service_enrollment_date', sa.String(length=255), nullable=True),
    sa.Column('service_reenrollment_date', sa.String(length=255), nullable=True),
    sa.Column('medical_category', sa.String(length=255), nullable=True),
    sa.Column('discharge_cause', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(length=255), nullable=True),
    sa.Column('civil_education_type', sa.String(length=255), nullable=True),
    sa.Column('civil_education_detail', sa.String(length=255), nullable=True),
    sa.Column('sons_names', sa.Text(), nullable=True),
    sa.Column('daughters_names', sa.Text(), nullable=True),
    sa.Column('brothers_names', sa.Text(), nullable=True),
    sa.Column('sisters_names', sa.Text(), nullable=True),
    sa.Column('particulars_verified_by_sho_on', sa.String(length=255), nullable=True),
    sa.Column('particulars_verified_by_ssp_on', sa.String(length=255), nullable=True),
    sa.Column('police_khidmat_verification_on', sa.String(length=255), nullable=True),
    sa.Column('verified_by_khidmat_markaz', sa.String(length=255), nullable=True),
    sa.Column('signature_recording_officer', sa.Text(), nullable=True),
    sa.Column('signature_individual', sa.Text(), nullable=True),
    sa.Column('fss_number', sa.String(length=255), nullable=True),
    sa.Column('fss_name', sa.String(length=255), nullable=True),
    sa.Column('fss_so', sa.String(length=255), nullable=True),
    sa.Column('original_doc_held', sa.Text(), nullable=True),
    sa.Column('documents_handed_over_to', sa.String(length=255), nullable=True),
    sa.Column('photo_on_document', sa.String(length=255), nullable=True),
    sa.Column('eobi_no', sa.String(length=255), nullable=True),
    sa.Column('insurance', sa.String(length=255), nullable=True),
    sa.Column('social_security', sa.String(length=255), nullable=True),
    sa.Column('home_contact_no', sa.String(length=255), nullable=True),
    sa.Column('police_training_letter_date', sa.String(length=255), nullable=True),
    sa.Column('vaccination_certificate', sa.String(length=255), nullable=True),
    sa.Column('volume_no', sa.String(length=255), nullable=True),
    sa.Column('payments', sa.Text(), nullable=True),
    sa.Column('fingerprint_attested_by', sa.String(length=255), nullable=True),
    sa.Column('date_of_entry', sa.String(length=255), nullable=True),
    sa.Column('card_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('employees2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=255), nullable=True),
    sa.Column('fss_no', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('service_rank', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=255), nullable=True),
    sa.Column('status2', sa.String(length=255), nullable=True),
    sa.Column('unit2', sa.String(length=255), nullable=True),
    sa.Column('rank2', sa.String(length=255), nullable=True),
    sa.Column('cnic', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.String(length=255), nullable=True),
    sa.Column('cnic_expiry', sa.String(length=255), nullable=True),
    sa.Column('documents_held', sa.Text(), nullable=True),
    sa.Column('documents_handed_over_to', sa.Text(), nullable=True),
    sa.Column('photo_on_doc', sa.String(length=255), nullable=True),
    sa.Column('eobi_no', sa.String(length=255), nullable=True),
    sa.Column('insurance', sa.String(length=255), nullable=True),
    sa.Column('social_security', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=255), nullable=True),
    sa.Column('home_contact', sa.String(length=255), nullable=True),
    sa.Column('verified_by_sho', sa.String(length=255), nullable=True),
    sa.Column('verified_by_khidmat_markaz', sa.String(length=255), nullable=True),
    sa.Column('domicile', sa.String(length=255), nullable=True),
    sa.Column('verified_by_ssp', sa.String(length=255), nullable=True),
    sa.Column('enrolled', sa.String(length=255), nullable=True),
    sa.Column('re_enrolled', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('post_office', sa.String(length=255), nullable=True),
    sa.Column('thana', sa.String(length=255), nullable=True),
    sa.Column('tehsil', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('duty_location', sa.String(length=255), nullable=True),
    sa.Column('police_trg_ltr_date', sa.String(length=255), nullable=True),
    sa.Column('vaccination_cert', sa.String(length=255), nullable=True),
    sa.Column('vol_no', sa.String(length=255), nullable=True),
    sa.Column('payments', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('allocation_status', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('cnic_attachment', sa.String(length=255), nullable=True),
    sa.Column('domicile_attachment', sa.String(length=255), nullable=True),
    sa.Column('sho_verified_attachment', sa.String(length=255), nullable=True),
    sa.Column('ssp_verified_attachment', sa.String(length=255), nullable=True),
    sa.Column('khidmat_verified_attachment', sa.String(length=255), nullable=True),
    sa.Column('police_trg_attachment', sa.String(length=255), nullable=True),
    sa.Column('bank_accounts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees2_cnic'), 'employees2', ['cnic'], unique=False)
    op.create_index(op.f('ix_employees2_fss_no'), 'employees2', ['fss_no'], unique=False)
    op.create_index(op.f('ix_employees2_id'), 'employees2', ['id'], unique=False)
    op.create_index(op.f('ix_employees2_serial_no'), 'employees2', ['serial_no'], unique=False)
    op.create_table('finance_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_accounts_account_type'), 'finance_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_finance_accounts_code'), 'finance_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_finance_accounts_id'), 'finance_accounts', ['id'], unique=False)
    op.create_table('finance_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_journal_entries_entry_date'), 'finance_journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_entry_no'), 'finance_journal_entries', ['entry_no'], unique=True)
    op.create_index(op.f('ix_finance_journal_entries_id'), 'finance_journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_source_id'), 'finance_journal_entries', ['source_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_source_type'), 'finance_journal_entries', ['source_type'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_status'), 'finance_journal_entries', ['status'], unique=False)
    op.create_table('fuel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_entries_id'), 'fuel_entries', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_vehicle_id'), 'fuel_entries', ['vehicle_id'], unique=False)
    op.create_table('general_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('storage_location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_items_id'), 'general_items', ['id'], unique=False)
    op.create_index(op.f('ix_general_items_item_code'), 'general_items', ['item_code'], unique=True)
    op.create_table('inventory_assignments_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_assignments_state_id'), 'inventory_assignments_state', ['id'], unique=False)
    op.create_table('leave_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_periods_employee_id'), 'leave_periods', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_periods_from_date'), 'leave_periods', ['from_date'], unique=False)
    op.create_index(op.f('ix_leave_periods_id'), 'leave_periods', ['id'], unique=False)
    op.create_index(op.f('ix_leave_periods_to_date'), 'leave_periods', ['to_date'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_permissions_key')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=False)
    op.create_table('restricted_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_serial_tracked', sa.Boolean(), nullable=True),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('make_model', sa.String(length=200), nullable=True),
    sa.Column('caliber', sa.String(length=50), nullable=True),
    sa.Column('storage_location', sa.String(length=120), nullable=True),
    sa.Column('requires_maintenance', sa.Boolean(), nullable=True),
    sa.Column('requires_cleaning', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricted_items_id'), 'restricted_items', ['id'], unique=False)
    op.create_index(op.f('ix_restricted_items_item_code'), 'restricted_items', ['item_code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('employee_ids', sa.Text(), nullable=False),
    sa.Column('route_stops', sa.Text(), nullable=True),
    sa.Column('route_from', sa.String(length=200), nullable=False),
    sa.Column('route_to', sa.String(length=200), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='Incomplete', nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('rate_per_km', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_id'), 'vehicle_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_table('vehicle_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('service_vendor', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenance_employee_id'), 'vehicle_maintenance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_id'), 'vehicle_maintenance', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_vehicle_id'), 'vehicle_maintenance', ['vehicle_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('make_model', sa.String(length=200), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('chassis_number', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('compliance', sa.String(length=50), nullable=False),
    sa.Column('government_permit', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=True)
    op.create_table('client_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=30), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_addresses_client_id'), 'client_addresses', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_addresses_id'), 'client_addresses', ['id'], unique=False)
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_id'), 'client_contacts', ['id'], unique=False)
    op.create_table('client_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.String(length=30), nullable=True),
    sa.Column('billing_cycle', sa.String(length=30), nullable=True),
    sa.Column('payment_terms', sa.String(length=30), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('penalty_overtime_rules', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contracts_client_id'), 'client_contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_contracts_contract_number'), 'client_contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_client_contracts_id'), 'client_contracts', ['id'], unique=False)
    op.create_table('client_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=300), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_documents_client_id'), 'client_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_documents_id'), 'client_documents', ['id'], unique=False)
    op.create_table('client_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('billing_period', sa.String(length=80), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('net_payable', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_invoices_client_id'), 'client_invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_invoices_id'), 'client_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_client_invoices_invoice_number'), 'client_invoices', ['invoice_number'], unique=True)
    op.create_table('client_rate_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('guard_type', sa.String(length=50), nullable=False),
    sa.Column('rate_per_shift_day_month', sa.Float(), nullable=False),
    sa.Column('overtime_rate', sa.Float(), nullable=True),
    sa.Column('holiday_rate', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_rate_cards_client_id'), 'client_rate_cards', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_rate_cards_id'), 'client_rate_cards', ['id'], unique=False)
    op.create_table('client_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('site_address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('site_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_sites_client_id'), 'client_sites', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_sites_id'), 'client_sites', ['id'], unique=False)
    op.create_table('employee_advance_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_db_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_db_id', 'month', name='uq_employee_advance_deduction_employee_month')
    )
    op.create_index(op.f('ix_employee_advance_deductions_employee_db_id'), 'employee_advance_deductions', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_employee_advance_deductions_id'), 'employee_advance_deductions', ['id'], unique=False)
    op.create_index(op.f('ix_employee_advance_deductions_month'), 'employee_advance_deductions', ['month'], unique=False)
    op.create_table('employee_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_db_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_advances_employee_db_id'), 'employee_advances', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_employee_advances_id'), 'employee_advances', ['id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_db_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_documents_employee_db_id'), 'employee_documents', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.create_table('employee_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_db_id', sa.Integer(), nullable=False),
    sa.Column('warning_number', sa.String(length=100), nullable=False),
    sa.Column('found_with', sa.Text(), nullable=True),
    sa.Column('notice_text', sa.Text(), nullable=True),
    sa.Column('supervisor_signature', sa.String(length=255), nullable=True),
    sa.Column('supervisor_signature_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_warnings_employee_db_id'), 'employee_warnings', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_employee_warnings_id'), 'employee_warnings', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['finance_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_account_id'), 'expenses', ['account_id'], unique=False)
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_journal_entry_id'), 'expenses', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_table('finance_journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(debit > 0) OR (credit > 0)', name='ck_fin_journal_line_one_side'),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name='ck_fin_journal_line_not_both'),
    sa.CheckConstraint('credit >= 0', name='ck_fin_journal_line_credit_nonneg'),
    sa.CheckConstraint('debit >= 0', name='ck_fin_journal_line_debit_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['finance_journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_journal_lines_account_id'), 'finance_journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_lines_employee_id'), 'finance_journal_lines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_lines_entry_id'), 'finance_journal_lines', ['entry_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_lines_id'), 'finance_journal_lines', ['id'], unique=False)
    op.create_table('general_item_employee_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('quantity_issued', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['general_items.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_item_employee_balances_employee_id'), 'general_item_employee_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_general_item_employee_balances_id'), 'general_item_employee_balances', ['id'], unique=False)
    op.create_index(op.f('ix_general_item_employee_balances_item_code'), 'general_item_employee_balances', ['item_code'], unique=False)
    op.create_table('general_item_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('condition_note', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['general_items.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_item_transactions_employee_id'), 'general_item_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_general_item_transactions_id'), 'general_item_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_general_item_transactions_item_code'), 'general_item_transactions', ['item_code'], unique=False)
    op.create_table('payroll_payment_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('employee_db_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('net_pay_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'employee_id', name='uq_payroll_payment_month_employee')
    )
    op.create_index(op.f('ix_payroll_payment_status_employee_db_id'), 'payroll_payment_status', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_payroll_payment_status_employee_id'), 'payroll_payment_status', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_payment_status_id'), 'payroll_payment_status', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_payment_status_month'), 'payroll_payment_status', ['month'], unique=False)
    op.create_table('payroll_sheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_db_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('pre_days_override', sa.Integer(), nullable=True),
    sa.Column('cur_days_override', sa.Integer(), nullable=True),
    sa.Column('leave_encashment_days', sa.Integer(), nullable=False),
    sa.Column('allow_other', sa.Float(), nullable=False),
    sa.Column('eobi', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('fine_adv_extra', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('bank_cash', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_db_id', 'from_date', 'to_date', name='uq_payroll_sheet_entries_employee_period')
    )
    op.create_index(op.f('ix_payroll_sheet_entries_employee_db_id'), 'payroll_sheet_entries', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_payroll_sheet_entries_from_date'), 'payroll_sheet_entries', ['from_date'], unique=False)
    op.create_index(op.f('ix_payroll_sheet_entries_id'), 'payroll_sheet_entries', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_sheet_entries_to_date'), 'payroll_sheet_entries', ['to_date'], unique=False)
    op.create_table('restricted_item_employee_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('quantity_issued', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['restricted_items.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricted_item_employee_balances_employee_id'), 'restricted_item_employee_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_restricted_item_employee_balances_id'), 'restricted_item_employee_balances', ['id'], unique=False)
    op.create_index(op.f('ix_restricted_item_employee_balances_item_code'), 'restricted_item_employee_balances', ['item_code'], unique=False)
    op.create_table('restricted_item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['restricted_items.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricted_item_images_id'), 'restricted_item_images', ['id'], unique=False)
    op.create_index(op.f('ix_restricted_item_images_item_code'), 'restricted_item_images', ['item_code'], unique=False)
    op.create_table('restricted_item_serial_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_to_employee_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['restricted_items.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricted_item_serial_units_id'), 'restricted_item_serial_units', ['id'], unique=False)
    op.create_index(op.f('ix_restricted_item_serial_units_issued_to_employee_id'), 'restricted_item_serial_units', ['issued_to_employee_id'], unique=False)
    op.create_index(op.f('ix_restricted_item_serial_units_item_code'), 'restricted_item_serial_units', ['item_code'], unique=False)
    op.create_index(op.f('ix_restricted_item_serial_units_serial_number'), 'restricted_item_serial_units', ['serial_number'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vehicle_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_id'), 'vehicle_documents', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    op.create_table('vehicle_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_images_id'), 'vehicle_images', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_images_vehicle_id'), 'vehicle_images', ['vehicle_id'], unique=False)
    op.create_table('client_guard_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('guard_type', sa.String(length=50), nullable=False),
    sa.Column('number_of_guards', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.String(length=30), nullable=True),
    sa.Column('shift_start', sa.String(length=20), nullable=True),
    sa.Column('shift_end', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('preferred_language', sa.String(length=80), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('weekly_off_rules', sa.String(length=200), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['client_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_guard_requirements_id'), 'client_guard_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_client_guard_requirements_site_id'), 'client_guard_requirements', ['site_id'], unique=False)
    op.create_table('employee_warning_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warning_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warning_id'], ['employee_warnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_warning_documents_id'), 'employee_warning_documents', ['id'], unique=False)
    op.create_index(op.f('ix_employee_warning_documents_warning_id'), 'employee_warning_documents', ['warning_id'], unique=False)
    op.create_table('restricted_item_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('serial_unit_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('condition_note', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['restricted_items.item_code'], ),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['restricted_item_serial_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricted_item_transactions_employee_id'), 'restricted_item_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_restricted_item_transactions_id'), 'restricted_item_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_restricted_item_transactions_item_code'), 'restricted_item_transactions', ['item_code'], unique=False)
    op.create_index(op.f('ix_restricted_item_transactions_serial_unit_id'), 'restricted_item_transactions', ['serial_unit_id'], unique=False)
    op.create_table('client_site_guard_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('employee_db_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['client_contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_db_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['client_guard_requirements.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['client_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_site_guard_allocations_contract_id'), 'client_site_guard_allocations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_client_site_guard_allocations_employee_db_id'), 'client_site_guard_allocations', ['employee_db_id'], unique=False)
    op.create_index(op.f('ix_client_site_guard_allocations_id'), 'client_site_guard_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_client_site_guard_allocations_requirement_id'), 'client_site_guard_allocations', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_client_site_guard_allocations_site_id'), 'client_site_guard_allocations', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_site_guard_allocations_site_id'), table_name='client_site_guard_allocations')
    op.drop_index(op.f('ix_client_site_guard_allocations_requirement_id'), table_name='client_site_guard_allocations')
    op.drop_index(op.f('ix_client_site_guard_allocations_id'), table_name='client_site_guard_allocations')
    op.drop_index(op.f('ix_client_site_guard_allocations_employee_db_id'), table_name='client_site_guard_allocations')
    op.drop_index(op.f('ix_client_site_guard_allocations_contract_id'), table_name='client_site_guard_allocations')
    op.drop_table('client_site_guard_allocations')
    op.drop_index(op.f('ix_restricted_item_transactions_serial_unit_id'), table_name='restricted_item_transactions')
    op.drop_index(op.f('ix_restricted_item_transactions_item_code'), table_name='restricted_item_transactions')
    op.drop_index(op.f('ix_restricted_item_transactions_id'), table_name='restricted_item_transactions')
    op.drop_index(op.f('ix_restricted_item_transactions_employee_id'), table_name='restricted_item_transactions')
    op.drop_table('restricted_item_transactions')
    op.drop_index(op.f('ix_employee_warning_documents_warning_id'), table_name='employee_warning_documents')
    op.drop_index(op.f('ix_employee_warning_documents_id'), table_name='employee_warning_documents')
    op.drop_table('employee_warning_documents')
    op.drop_index(op.f('ix_client_guard_requirements_site_id'), table_name='client_guard_requirements')
    op.drop_index(op.f('ix_client_guard_requirements_id'), table_name='client_guard_requirements')
    op.drop_table('client_guard_requirements')
    op.drop_index(op.f('ix_vehicle_images_vehicle_id'), table_name='vehicle_images')
    op.drop_index(op.f('ix_vehicle_images_id'), table_name='vehicle_images')
    op.drop_table('vehicle_images')
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_id'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_restricted_item_serial_units_serial_number'), table_name='restricted_item_serial_units')
    op.drop_index(op.f('ix_restricted_item_serial_units_item_code'), table_name='restricted_item_serial_units')
    op.drop_index(op.f('ix_restricted_item_serial_units_issued_to_employee_id'), table_name='restricted_item_serial_units')
    op.drop_index(op.f('ix_restricted_item_serial_units_id'), table_name='restricted_item_serial_units')
    op.drop_table('restricted_item_serial_units')
    op.drop_index(op.f('ix_restricted_item_images_item_code'), table_name='restricted_item_images')
    op.drop_index(op.f('ix_restricted_item_images_id'), table_name='restricted_item_images')
    op.drop_table('restricted_item_images')
    op.drop_index(op.f('ix_restricted_item_employee_balances_item_code'), table_name='restricted_item_employee_balances')
    op.drop_index(op.f('ix_restricted_item_employee_balances_id'), table_name='restricted_item_employee_balances')
    op.drop_index(op.f('ix_restricted_item_employee_balances_employee_id'), table_name='restricted_item_employee_balances')
    op.drop_table('restricted_item_employee_balances')
    op.drop_index(op.f('ix_payroll_sheet_entries_to_date'), table_name='payroll_sheet_entries')
    op.drop_index(op.f('ix_payroll_sheet_entries_id'), table_name='payroll_sheet_entries')
    op.drop_index(op.f('ix_payroll_sheet_entries_from_date'), table_name='payroll_sheet_entries')
    op.drop_index(op.f('ix_payroll_sheet_entries_employee_db_id'), table_name='payroll_sheet_entries')
    op.drop_table('payroll_sheet_entries')
    op.drop_index(op.f('ix_payroll_payment_status_month'), table_name='payroll_payment_status')
    op.drop_index(op.f('ix_payroll_payment_status_id'), table_name='payroll_payment_status')
    op.drop_index(op.f('ix_payroll_payment_status_employee_id'), table_name='payroll_payment_status')
    op.drop_index(op.f('ix_payroll_payment_status_employee_db_id'), table_name='payroll_payment_status')
    op.drop_table('payroll_payment_status')
    op.drop_index(op.f('ix_general_item_transactions_item_code'), table_name='general_item_transactions')
    op.drop_index(op.f('ix_general_item_transactions_id'), table_name='general_item_transactions')
    op.drop_index(op.f('ix_general_item_transactions_employee_id'), table_name='general_item_transactions')
    op.drop_table('general_item_transactions')
    op.drop_index(op.f('ix_general_item_employee_balances_item_code'), table_name='general_item_employee_balances')
    op.drop_index(op.f('ix_general_item_employee_balances_id'), table_name='general_item_employee_balances')
    op.drop_index(op.f('ix_general_item_employee_balances_employee_id'), table_name='general_item_employee_balances')
    op.drop_table('general_item_employee_balances')
    op.drop_index(op.f('ix_finance_journal_lines_id'), table_name='finance_journal_lines')
    op.drop_index(op.f('ix_finance_journal_lines_entry_id'), table_name='finance_journal_lines')
    op.drop_index(op.f('ix_finance_journal_lines_employee_id'), table_name='finance_journal_lines')
    op.drop_index(op.f('ix_finance_journal_lines_account_id'), table_name='finance_journal_lines')
    op.drop_table('finance_journal_lines')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_journal_entry_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_account_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_employee_warnings_id'), table_name='employee_warnings')
    op.drop_index(op.f('ix_employee_warnings_employee_db_id'), table_name='employee_warnings')
    op.drop_table('employee_warnings')
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_db_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employee_advances_id'), table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_employee_db_id'), table_name='employee_advances')
    op.drop_table('employee_advances')
    op.drop_index(op.f('ix_employee_advance_deductions_month'), table_name='employee_advance_deductions')
    op.drop_index(op.f('ix_employee_advance_deductions_id'), table_name='employee_advance_deductions')
    op.drop_index(op.f('ix_employee_advance_deductions_employee_db_id'), table_name='employee_advance_deductions')
    op.drop_table('employee_advance_deductions')
    op.drop_index(op.f('ix_client_sites_id'), table_name='client_sites')
    op.drop_index(op.f('ix_client_sites_client_id'), table_name='client_sites')
    op.drop_table('client_sites')
    op.drop_index(op.f('ix_client_rate_cards_id'), table_name='client_rate_cards')
    op.drop_index(op.f('ix_client_rate_cards_client_id'), table_name='client_rate_cards')
    op.drop_table('client_rate_cards')
    op.drop_index(op.f('ix_client_invoices_invoice_number'), table_name='client_invoices')
    op.drop_index(op.f('ix_client_invoices_id'), table_name='client_invoices')
    op.drop_index(op.f('ix_client_invoices_client_id'), table_name='client_invoices')
    op.drop_table('client_invoices')
    op.drop_index(op.f('ix_client_documents_id'), table_name='client_documents')
    op.drop_index(op.f('ix_client_documents_client_id'), table_name='client_documents')
    op.drop_table('client_documents')
    op.drop_index(op.f('ix_client_contracts_id'), table_name='client_contracts')
    op.drop_index(op.f('ix_client_contracts_contract_number'), table_name='client_contracts')
    op.drop_index(op.f('ix_client_contracts_client_id'), table_name='client_contracts')
    op.drop_table('client_contracts')
    op.drop_index(op.f('ix_client_contacts_id'), table_name='client_contacts')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_client_addresses_id'), table_name='client_addresses')
    op.drop_index(op.f('ix_client_addresses_client_id'), table_name='client_addresses')
    op.drop_table('client_addresses')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_maintenance_vehicle_id'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_id'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_employee_id'), table_name='vehicle_maintenance')
    op.drop_table('vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_id'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_restricted_items_item_code'), table_name='restricted_items')
    op.drop_index(op.f('ix_restricted_items_id'), table_name='restricted_items')
    op.drop_table('restricted_items')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_leave_periods_to_date'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_id'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_from_date'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_employee_id'), table_name='leave_periods')
    op.drop_table('leave_periods')
    op.drop_index(op.f('ix_inventory_assignments_state_id'), table_name='inventory_assignments_state')
    op.drop_table('inventory_assignments_state')
    op.drop_index(op.f('ix_general_items_item_code'), table_name='general_items')
    op.drop_index(op.f('ix_general_items_id'), table_name='general_items')
    op.drop_table('general_items')
    op.drop_index(op.f('ix_fuel_entries_vehicle_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_id'), table_name='fuel_entries')
    op.drop_table('fuel_entries')
    op.drop_index(op.f('ix_finance_journal_entries_status'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_source_type'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_source_id'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_id'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_entry_no'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_entry_date'), table_name='finance_journal_entries')
    op.drop_table('finance_journal_entries')
    op.drop_index(op.f('ix_finance_accounts_id'), table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_code'), table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_account_type'), table_name='finance_accounts')
    op.drop_table('finance_accounts')
    op.drop_index(op.f('ix_employees2_serial_no'), table_name='employees2')
    op.drop_index(op.f('ix_employees2_id'), table_name='employees2')
    op.drop_index(op.f('ix_employees2_fss_no'), table_name='employees2')
    op.drop_index(op.f('ix_employees2_cnic'), table_name='employees2')
    op.drop_table('employees2')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
